security:
  oauth2:
    resource:
      filter-order: 3
server:
  port: 9200
spring:
  application:
    name: lyb-auth
eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/